### ISSUE TITLE
@example build出来的页面出现两个示例，示例代码依然没有高亮

### ISSUE THREAD

**Issue by Ellery0924** [YMFE/ydoc#15]
RT

**Comment by dwb1994** [comment]
@Ellery0924  需要在配置文件里配置defaultGrammer，或者在注释块中配置@examplelanguage

**Comment by Ellery0924** [comment]
@examplelanguage javascript 这个该咋写？现在试了jsx js javascript都没有作用

**Comment by dwb1994** [comment]
是不是没更新到v3.0.0版本啊？js javascript都可以被解析成javascript的。
* @examplelanguage js 即可

**Comment by Ellery0924** [comment]
是3.0..

**Comment by Ellery0924** [comment]
beta tag已经安装测试，bug解决了

**Comment by Ellery0924** [comment]
多谢文博！
