### ISSUE TITLE
表格生成有问题

### ISSUE THREAD

**Issue by xupaopaopaopao** [YMFE/ydoc#18]
当用 markdown 生成文档的时候，如果使用表格，表格最后一行的最后一项如果为空，则显示不正确
![image](https://user-images.githubusercontent.com/11606028/28568140-523e0e18-7167-11e7-8f31-4be3536d1bdf.png)

**Comment by dwb1994** [comment]
https://github.com/chjj/marked/pull/697 
ydoc 使用的 marked 解析 markdown，这个问题是 marked 解析错误，最新版的 marked 仍未解决这个问题。

暂时问题不大的情况下，最后一行多写一个格子来弥补吧：
``` markdown
| 参数      |    类型    | 描述  |
| :------  | :-------- | :----- |
| name    |  string    |         |
| option   |  object   |         |         |
```

后面 ydoc 重构的时候再调研，可能使用 remarkable 替代 marked。

**Comment by dwb1994** [comment]
@xupaopaopaopao v4.0.0 版本已修复这个问题 😜
