### ISSUE TITLE
新需求：增加 build 时间戳

### ISSUE THREAD

**Issue by Ceelog** [YMFE/ydoc#20]
希望可以在首页显示最新 build 的时间，这样用户就知道文档是否为最新的。

**Comment by hellosean1025** [comment]
可参考下 yapi 文档，https://yapi.ymfe.org
首页文档源码：https://github.com/YMFE/yapi/blob/master/docs/index.jsx

我们是在 banner 增加了当前的版本编号，当然你也可以使用时间戳

**Comment by Ceelog** [comment]
靠谱
