### ISSUE TITLE
ydoc serve 命令只能执行一次，后面必挂

### ISSUE THREAD

**Issue by alvin198761** [YMFE/ydoc#25]
### YDoc 版本号: 
~
 v4.0.3
### 环境(操作系统、Node 版本、浏览器版本等信息): 
~
windows 10 家庭版 x64
npm : 5.3.0
node: 8.3.0
chrome 版本 70.0.3538.77（正式版本） （64 位）

### 复现步骤: 
~
ydoc init 创建项目

ydoc serve 启动 
访问正常

然后 ctrl +c 停止

然后
ydoc serve  
再也没有成功过
### 期望结果: 
~
每次都能正常执行
### 补充说明: 
~
没有ydoc serve 的话，我不可能考虑用这个，

**Comment by alvin198761** [comment]
补充错误信息：

F:\2018_dir\ydoc>ydoc serve
\ events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EPERM
    at _errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)

**Comment by dwb1994** [comment]
@alvin198761 升级下最新版试试？

**Comment by zsmj1994** [comment]
还是遇到了..
