### ISSUE TITLE
在示例Demo中执行ydoc serve报错

### ISSUE THREAD

**Issue by Joannzhou** [YMFE/ydoc#29]
### YDoc 版本号: 
~4.1.0

### 环境(操作系统、Node 版本、浏览器版本等信息): 
~windows 10, node10.15.0

### 复现步骤: 
~在Excamples/homepage目录下执行ydoc serve报错

events.js:167
      throw er; // Unhandled 'error' event
      ^
![11EB0210-440E-4739-A52C-CB72065DE75D](https://user-images.githubusercontent.com/3230881/57212494-77063e00-7016-11e9-99a2-b97f102c1c81.png)

Error: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event at:
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12)

### 期望结果: 
~

### 补充说明: 
~

**Comment by MJLandYFF** [comment]
我也是这个情况，有解决方案么

**Comment by hellosean1025** [comment]
建议使用 mac, linux

**Comment by ZGarry** [comment]
同win10系统，遇到了同样问题
