### ISSUE TITLE
ydoc serve报错

### ISSUE THREAD

**Issue by XingeWang** [YMFE/ydoc#30]
### YDoc 版本号: 
~4.1.0

### 环境(操作系统、Node 版本、浏览器版本等信息): 
~win7 64位 ,node(8.16.0), npm(6.4.1)

### 复现步骤: 
~ydoc init(成功)
~ydoc build(成功)
~ydoc serve(失败)，报错
`\ events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EPERM
    at FSEvent.FSWatcher._handle.onchange (fs.js:1359:9)
`

### 期望结果: 
~成功，提示可以在浏览器地址127.0.0.1：9999访问

### 补充说明: 
~

**Comment by hellosean1025** [comment]
建议使用 mac ，linux

**Comment by XingeWang** [comment]
现在在windows的一种可行方案就是,当报上面这个错的时候,直接删掉编译好的文件夹.site,然后重新ydoc serve就可以了,或者中途突然挂掉等问题,都可以采用这种方式.
