### ISSUE TITLE
https://ydoc.ymfe.org/进不去

### ISSUE THREAD

**Issue by XingeWang** [YMFE/ydoc#32]
### YDoc 版本号: 
~

### 环境(操作系统、Node 版本、浏览器版本等信息): 
~

### 复现步骤: 
~

### 期望结果: 
~

### 补充说明: 
~

**Comment by hellosean1025** [comment]
https://hellosean1025.github.io/ydoc

**Comment by hellosean1025** [comment]
@XingeWang

**Comment by XingeWang** [comment]
百度搜索出来的ydoc官网还是链接到了https://ydoc.ymfe.org/(打不开),用你发的这个地址可以了感谢
