### ISSUE TITLE
插件导入成功，但是仍旧无法看到结果

### ISSUE THREAD

**Issue by ZGarry** [YMFE/ydoc#39]
我在尝试导入demo插件的时候，成功导入了，但是demo插件却未产生任何效果

![image](https://user-images.githubusercontent.com/43488431/76847047-6c464780-687c-11ea-9c3a-6261d913e8cf.png)

![image](https://user-images.githubusercontent.com/43488431/76848140-21c5ca80-687e-11ea-9d15-37c70173009e.png)

我预期的效果应当是将书换成<book
![image](https://user-images.githubusercontent.com/43488431/76848033-f5aa4980-687d-11ea-9374-438625c6203a.png)

**Comment by ZGarry** [comment]
自己主要是做开发后端，对npm体系不大了解，希望能获得解答～

**Comment by dwb1994** [comment]
@ZGarry 升级到 ydoc@4.1.2 版本再试一下，新版解决了这个 bug
