### ISSUE TITLE
开发建议：是否考虑出一个纯文本站点模式，类似于gitbook

### ISSUE THREAD

**Issue by ZGarry** [YMFE/ydoc#45]
像是gitbook一样，没有首页，仅仅有一个页面。用来浏览书本。

我感觉ydoc在纯文本建站上的体验，已经碾压了gitbook，我个人也用ydoc建过一些说明性质网站了。很期待ydoc的发展。

但是目前虽然有首页，但首页的图标不能很方便设置与替换。而且很多用户可能和我一样，大多数时候需要得可能是一个最简单的单页面。

希望未来能予以考虑！

**Comment by dwb1994** [comment]
非常感谢你的支持，按照我的理解，你想要的可能是：[首页使用 markdown](https://hellosean1025.github.io/ydoc/examples/homepage/index.html)

ydoc 提供了这个 demo，**首页可以直接使用 markdown 文件**

如果不需要导航的话，不配置导航即可，这样就是一个最简单的基于 markdown 的单页面了
