### ISSUE TITLE
安装完后，没有ydoc命令

### ISSUE THREAD

**Issue by pandabajie** [YMFE/ydoc#47]
### YDoc 版本号: 
~ydoc@4.1.2

### 环境(操作系统、Node 版本、浏览器版本等信息): 
~centos7, Node 版本 v10.16.0

### 复现步骤: 
~ 安装完后，没有ydoc命令

### 期望结果: 
~ 能正常执行ydoc init

### 补充说明: 
~

**Comment by dwb1994** [comment]
npm install 命令是不是没有加 -g ？
如果不是，请详细描述下安装过程和结果
