### ISSUE TITLE
http://md.corp.qunar.com/ 打不开

### ISSUE THREAD

**Issue by tuntun5011** [YMFE/ydoc#48]
从http://ued.qunar.com/yis/index.html 进去的所有链接基本上都打不开，http://ued.qunar.com/yis/start/start.html 还维护吗？

**Comment by ittce** [comment]
我刚才用手机试了下， yis这个地址是可以打开的啊。

**Comment by ittce** [comment]
md.corp.qunar.com 这个是我们内部注册应用的平台。 外网是访问不了的。 你可以从注册应用的后面看起。

**Comment by tuntun5011** [comment]
![屏幕快照 2020-12-29 下午3 08 56](https://user-images.githubusercontent.com/34851309/103265114-c8cbbb00-49e7-11eb-9e78-d29c5fec3828.png)
但是后面构建应用需要这个平台生成的hybridId，，还是说YIS不是对外部开放的？

**Comment by ittce** [comment]
yis是打包成qp内置到去哪儿app内部的。
hyid和md平台是用来做打包发布，客户端热更新那块的。 这块都需要客户端支持。
目前内部技术rn为主。

**Comment by tuntun5011** [comment]
emm..你可能没太理解我的意思，http://ued.qunar.com/yis/start/start.html 这个网址的内容是第三方接入去哪儿的文档吧，既然可以接入，那为什么申请hybridId的网站不对外开放呢，接入方怎么接入呢？

**Comment by dwb1994** [comment]
@tuntun5011 YIS不是对外部开放的，md平台、hy2、qrn 都不是对外的
